name: imbsam
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - blas=1.0
  - ca-certificates=2022.12.7
  - certifi=2022.12.7
  - cudatoolkit=11.0.221
  - debugpy=1.5.1
  - decorator=5.1.1
  - entrypoints=0.4
  - flit-core=3.6.0
  - freetype=2.12.1
  - giflib=5.2.1
  - intel-openmp=2022.1.0
  - ipykernel=6.15.0
  - ipython=7.33.0
  - jedi=0.18.2
  - jpeg=9b
  - jupyter_client=7.0.6
  - jupyter_core=4.11.1
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=11.2.0
  - libpng=1.6.37
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtiff=4.1.0
  - libuv=1.40.0
  - libwebp=1.2.0
  - lz4-c=1.9.4
  - matplotlib-inline=0.1.6
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.14
  - mkl_random=1.0.4
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - ninja=1.10.2
  - ninja-base=1.10.2
  - openssl=1.1.1s
  - packaging=23.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.3.0
  - pip=22.3.1
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pygments=2.14.0
  - python=3.7.16
  - python-dateutil=2.8.2
  - python_abi=3.7
  - pytorch=1.7.1
  - pyzmq=19.0.2
  - readline=8.2
  - setuptools=65.6.3
  - six=1.16.0
  - sqlite=3.40.1
  - tk=8.6.12
  - torchaudio=0.7.2
  - torchvision=0.8.2
  - tornado=6.1
  - traitlets=5.9.0
  - typing_extensions=4.4.0
  - wcwidth=0.2.6
  - wheel=0.37.1
  - xz=5.2.10
  - zeromq=4.3.4
  - zlib=1.2.13
  - zstd=1.4.9
  - pip:
    - balanced-loss==0.1.0
    - blessed==1.20.0
    - click==8.0.4
    - cycler==0.11.0
    - et-xmlfile==1.1.0
    - fonttools==4.38.0
    - gpustat==1.0.0
    - imageio==2.25.0
    - importlib-metadata==6.0.0
    - joblib==1.2.0
    - kiwisolver==1.4.4
    - matplotlib==3.5.3
    - networkx==2.6.3
    - numpy==1.21.6
    - nvidia-ml-py==11.495.46
    - openpyxl==3.1.1
    - pandas==1.3.5
    - pyparsing==3.0.9
    - pytz==2022.7.1
    - pywavelets==1.3.0
    - scikit-image==0.19.3
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - seaborn==0.12.2
    - threadpoolctl==3.1.0
    - tifffile==2021.11.2
    - zipp==3.15.0